name: Azure OIDC Authentication Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Required to checkout the repository

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    
    # Optional: Specify an environment to use environment-specific credentials
    # environment: dev
    
    env:
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Azure login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Azure CLI action
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Now you can run any Azure CLI commands
            az account show
            az group show --name ${{ env.AZURE_RESOURCE_GROUP }}
      
      - name: Deploy Azure resources
        run: |
          # Example: Deploy an Azure resource
          az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file deployment/template.json \
            --parameters deployment/parameters.json
